<?php
   include_once "/home/nutrientnet/md/livefront/www/admin/include_path.php";
   include_once "$include_dir/config.php";
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>



</HEAD>
<BODY bgcolor=FFFFFF marginwidth=0 marginheight=0 leftmargin=0 topmargin=0>



<?php 
/* include "$include_dir/head_meta.php";
include "$include_dir/js_second_window.php"; */
?>  




<?php include "$include_dir/top.php"; ?>



<!-- END OF BANNER -->

<div id="page"> 


<!-- PUT TOP NAV BAR HERE -->
	
<table class="text" valign=top cell padding=0 border=0 width=1000px>
<tr><td>
<!-- <p align="center" class="text">Top Nav Bar HERE</p> -->
</td></tr>
</table>

<!-- END TOP NAV BAR HERE -->
	
<!-- BEGIN SETUP MAIN PAGE TABLE -->

<table class=text align=center cellpadding=0 cell spacing=0 border=0 width=1000>

<tr>

<!-- BND SETUP Main Page TABLE -->
 
<!-- BEGIN Left Panel Main Page PAGE CONTENT -->

<td valign="center" valign=center width=675px class=text>


<!-- BEGIN MAIN PAGE CONTENT -->

<table width=675 cellpadding=15>
<tr><td>
<h2 class="header_left_content">Are Certification and Verification required?</h2>

<p class="text_left_content">
Certification is required once a practice is installed to assure that implementation and practice standards are met.
</p>

<p class="text_left_content">
All trading contracts require annual credit verification and reporting.  Verification is required to assure that the practices <u>are</u> maintained and operating effectively.  For credits generated by annual practices, such as cover crops, inspections will be required a minimum of twice during the annual life.  For credits generated by structural BMPs inspections are required once per year.  
</p>

<p class="text_left_content">
In both cases, the inspections must be done by independent third parties.  Local Soil Conservation Districts can also provide inspection services.  In addition to the third-party inspections, MDA (or its designee) will perform annual spot-check inspections on a minimum of 10 percent of all traded agricultural credits.
</p>

</td></tr>
</table>

<!-- END MAIN PAGE CONTENT -->

</td>

<!-- BEGIN RIGHT NAV -->

<td width=300 cellpadding=10 valign="top">

<ul class="text_right_content">
<li><a href="http://www.mdnutrienttrading.com/">Maryland Nutrient Trading HOME</a>
</ul>

<p>&nbsp;</p>  

<p class="header_right_content" align=left>Farmers . . .</p>

<ul class="text_right_content">
<li><p><a href="http://www.mdnutrienttrading.com/farmers/">Interested in nutrient trading?</a></p>
<li><p><a href="http://www.mdnutrienttrading.com/farmers/q1.php">Am I eligible to participate?</a></p>
<li><p><a href="http://www.mdnutrienttrading.com/farmers/q2.php">What can I trade?</a></p>
<li><p><a href="http://www.mdnutrienttrading.com/farmers/q3.php">How do I sell Credits?</a></p>
<li><p><a href="http://www.mdnutrienttrading.com/farmers/q4.php">What are the requirements for developing Trade Agreements?</a></p>
<li><p>Are Certification and Verification required?</p>
<li><p><a href="http://www.mdnutrienttrading.com/farmers/q6.php">What is the role of the Conservation Districts?</a></p>
</ul>

  
</td>

<!-- END RIGHT NAV--></tr>

</table>

<!-- END MAIN PAGE -->


</div> <!--  Ends "page" div -->

<?php include "$include_dir/bottom.php"; ?>
