<?php
   include_once "/home/mda_http/mda/nutrad/admin/include_path.php";
   include_once "$include_dir/config.php";
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>



</HEAD>
<BODY bgcolor=FFFFFF marginwidth=0 marginheight=0 leftmargin=0 topmargin=0>



<?php 
/* include "$include_dir/head_meta.php";
include "$include_dir/js_second_window.php"; */
?>  




<?php include "$include_dir/top.php"; ?>



<!-- END OF BANNER -->

<div id="page"> 


<!-- PUT TOP NAV BAR HERE -->
	
<table class="text" valign=top cell padding=0 border=0 width=1000px>
<tr><td>
<!-- <p align="center" class="text">Top Nav Bar HERE</p> -->
</td></tr>
</table>

<!-- END TOP NAV BAR HERE -->
	
<!-- BEGIN SETUP MAIN PAGE TABLE -->

<table class=text cellpadding=0 cell spacing=0 border=0 width=1000px>

<tr>

<!-- BND SETUP Main Page TABLE -->
 
<!-- BEGIN Left Panel Main Page PAGE CONTENT -->

<td valign="center" valign=center width=675px class=text>


<!-- BEGIN MAIN PAGE CONTENT -->


<table width=675 cellpadding=15>
<tr><td>
<h2 class="header_left_content">Why become part of the Nutrient Trading Program?</h2>
<h2 class="header_left_content">&nbsp;&nbsp;&nbsp; <i><b>. . . Because it makes economic cents!</b></i></h2>

<p class="text_left_content">
Water quality trading is not a governmentally mandated program or a regulatory requirement. It is simply a market-based approach that gives those needing to maintain regulatory requirements an avenue to do so more cost-effectively. Water quality trading provides an opportunity for landowners and producersto receive incentives and compensation for implementing conservation practices. Trading provides additional resources that supplement existing conservation program funding. Farmers can sell the amount of nutrients reduced by conservation practices. New wastewater dischargers and existing dischargers of any size that want to grow beyond nutrient loading limits will have to do so through other mechanisms. One of these mechanisms is acquiring nonpoint source discharge credits or offsets.
</p>

<p class="text_left_content">
As part of the Chesapeake Bay Restoration Program, Maryland has agreed to drastically reduce the amount of nutrients (nitrogen and phosphorous) entering the Bay. Limits on the amount of nutrients that will be allowed in the state's rivers have been established in
  <a href="http://www.dnr.state.md.us/Bay/tribstrat/">Maryland's Tributary Strategies</a> and/or TMDL restrictions in some severely impacted watersheds. To achieve their nutrient reduction requirements under the Maryland Tributary Strategies or the TMDL in a watershed, wastewater treatment plants are required to reduce their discharges to state-of-the-art technology and to maintain those levels.
</p>

<p class="text_left_content">
The agricultural community has a similar requirement to reduce nutrient discharges from their operations to levels identified in the Tributary Strategies or a TMDL. By a combination of agronomic, land use, and/or structural practices (BMPs), farmers can meet this requirement ... and then some. The extra pounds of decreased nitrogen and phosphorous that can be generated by implementing additional BMPs can be sold as credits to those wastewater treatment plans or other entities needing additional nutrient reductions to offset their increased loads. By selling these credits, nutrient trading can be a source of new revenue for farmers.
</br>
<a href="http://mdnutrienttrading.org/farmers/moreinfo.php">more</a> . . .
</p>


<h2 class="header_left_content">What is the process?</h2>


<p class="text_left_content">
Maryland has established policies to govern how trading will take place.  Answers to the following key questions are provided to assist producers in understanding their role in water quality trading and the policies governing how the program operates.
</p>

<ol class="text_left_content">
<li><a href="http://mdnutrienttrading.org/farmers/q1.php">Am I eligible to participate?</a></li>
<li><a href="http://mdnutrienttrading.org/farmers/q2.php">What can I trade?</a></li>
<li><a href="http://mdnutrienttrading.org/farmers/q3.php">How do I sell credits?</a></li>
<li><a href="http://mdnutrienttrading.org/farmers/q4.php">What are the requirements for developing Trade Agreements?</a></li>
<li><a href="http://mdnutrienttrading.org/farmers/q5.php">Are Verification and Certification required?</a></li>
<li><a href="http://mdnutrienttrading.org/farmers/q6.php">What is the role of the Conservation Districts?</a></li>
</ol>

<p>&nbsp;</p>

<p class="text_left_content">
<i>Click on the video to learn more about the benefits of becoming an agricultural seller</i>
</p>
  
</td></tr>

<tr><td>
 <p class="text_left_content" Align="center">Marketing Video Placeholder</p>
</td>

</tr>
</table>



<!-- END MAIN PAGE CONTENT -->

</td>

<!-- BEGIN RIGHT NAV -->

<td width=300 cellpadding=10 valign="top">

<ul class="text_right_content">
<li><a href="http://mdnutrienttrading.org/">Maryland Nutrient Trading HOME</a>
</ul>

<p>&nbsp;</p>  

<p class="header_right_content" align=left>Farmers . . .</p>

<ul class="text_right_content">
<li><p>Interested in nutrient trading?</p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q1.php">Am I eligible to participate?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q2.php">What can I trade?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q3.php">How do I sell Credits?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q4.php">What are the requirements for developing Trade Agreements?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q5.php">Are Certification and Verification required?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q6.php">What is the role of the Conservation Districts?</a></p>
</ul>

<p>&nbsp;</p>

<p class="header_right_content" Align="center">For More information Contact:</p>
<p class="text_right_content" Align="center">John Rhoderick</br>
MD Department of Agriculture</br>
Office of Resource Conservation</br>
Phone: 410-841-5876</br>
E-mail: <a href="mailto:rhoderjc@mda.state.md.us">rhoderjc@mda.state.md.us</a></p>
<p class="text_right_content" Align="center">OR</p>
<p class="text_right_content" Align="center">Your Local Soil Conservation</br>
District Office</br>
(<a href="http://mdnutrienttrading.org/docs/SCDDirectory.pdf">Click Here</a> for directory)</p 
  
<p>&nbsp;</p>  

</td>

<!-- END RIGHT NAV-->
</tr>
</table>

<!-- END MAIN PAGE -->


</div> <!--  Ends "page" div -->

<?php include "$include_dir/bottom.php"; ?>
