<?php
   include_once "/home/mda_http/mda/nutrad/admin/include_path.php";
   include_once "$include_dir/config.php";
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>



</HEAD>
<BODY bgcolor=FFFFFF marginwidth=0 marginheight=0 leftmargin=0 topmargin=0>



<?php 
/* include "$include_dir/head_meta.php";
include "$include_dir/js_second_window.php"; */
?>  




<?php include "$include_dir/top.php"; ?>



<!-- END OF BANNER -->

<div id="page"> 


<!-- PUT TOP NAV BAR HERE -->
	
<table class="text" valign=top cell padding=0 border=0 width=1000px>
<tr><td>
<!-- <p align="center" class="text">Top Nav Bar HERE</p> -->
</td></tr>
</table>

<!-- END TOP NAV BAR HERE -->
	
<!-- BEGIN SETUP MAIN PAGE TABLE -->

<table class=text align=center cellpadding=0 cell spacing=0 border=0 width=1000>

<tr>

<!-- BND SETUP Main Page TABLE -->
 
<!-- BEGIN Left Panel Main Page PAGE CONTENT -->

<td valign="center" valign=center width=675px class=text>


<!-- BEGIN MAIN PAGE CONTENT -->

<table width=675 cellpadding=15>
<tr><td>
<h2 class="header_left_content">Why become part of the Nutrient Trading Program?</h2> 
<h2 class="header_left_content">&nbsp;&nbsp;&nbsp; <i><b>. . . Because it makes economic cents!</b></i></h2> 
</td></tr>

<tr><td>
<p class="text_left_content">
Water quality trading provides an opportunity for farmers and landowners to receive compensation for implementing conservation practices on their lands.  Trading provides additional resources that supplement existing conservation program funding.  Farmers sell the amount nutrients reduced by conservation practices.  Facilities, like wastewater treatment plants, buy the reductions to help meet regulatory requirements that limit the amount of nitrogen and phosphorous that may be discharged in their wastewater to local waterbodies.  These regulated facilities may find that it is less expensive to pay producers to implement conservation practices than it is to install enhanced treatment technologies.
</p>

<p class="text_left_content">
Water quality trading is not a governmentally mandated program or regulatory requirement.  It is simply a market-based tool that enables some industrial and municipal facilities to meet regulatory requirements more cost-effectively.  Through trading, producers receive incentives to implement conservation practices.
</p>

<p class="text_left_content">
As part of the Chesapeake Bay Restoration Program, Maryland has agreed to drastically reduce the amount of nutrients (nitrogen and phosphorous) entering the Bay. Limits on the amount of nutrients that will be allowed in the state's rivers have been established in <a href="http://www.dnr.state.md.us/Bay/tribstrat/">Maryland's Tributary Strategies</a> and TMDL restriction in some severely impacted watersheds.
</p>

<p class="text_left_content">
To achieve their nutrient reduction requirements under the Maryland Tributary Strategies or TMDL in a watershed, wastewater treatment plants are required to reduce their discharges to state-of-the art technology and to maintain those levels. New wastewater dischargers and existing dischargers of any size that want to grow beyond these nutrient loading limits will have to do so through other mechanisms. One of these mechanisms is acquiring nonpoint source discharge credits or offsets. 
</p>

<p class="text_left_content">
The agricultural community has a similar requirement to reduce nutrient discharges from their operations to levels identified in the Tributary Strategies or a TMDL. By a combination of agronomics management options and/or Best Management Practices (BMPs), farmers can meet this requirement ... and then some. The extra pounds of decreased nitrogen and phosphorous that can be generated by implementing additional BMPs can be sold as credits to those wastewater treatment plans needing additional nutrient reductions to offset their increased load. By selling these credits, nutrient trading can be a source of new revenue for farmers.
</p>

<p class="text_left_content">
Each landowner and farmer will have options to select from a suite of practices for generating credits for their operation. These include changes in land use oragronomic practices (typical farming operations that involved planting and harvesting of crops) and installing additional structural best management practices (BMPs) (where farmers/landowners build a specific structure to reduce runoff and nutrients).
</p>
</td></tr>
</table>
<!-- END MAIN PAGE CONTENT -->

</td>

<!-- BEGIN RIGHT NAV -->

<td width=300 cellpadding=10 valign="top">

<ul class="text_right_content">
<li><a href="http://mdnutrienttrading.org/">Maryland Nutrient Trading HOME</a>
</ul>

<p>&nbsp;</p>  

<p class="header_right_content" align=left>Farmers . . .</p>

<ul class="text_right_content">
<li><p><a href="http://mdnutrienttrading.org/farmers/">Interested in nutrient trading?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q1.php">Am I eligible to participate?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q2.php">What can I trade?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q3.php">How do I sell Credits?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q4.php">What are the requirements for developing Trade Agreements?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q5.php">Are Verification and Certification required?</a></p>
<li><p><a href="http://mdnutrienttrading.org/farmers/q6.php">What is the role of the Conservation Districts?</a></p>
</ul>

  
</td>

<!-- END RIGHT NAV--></tr>

</table>

<!-- END MAIN PAGE -->


</div> <!--  Ends "page" div -->

<?php include "$include_dir/bottom.php"; ?>